server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/eventdb
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
